apiVersion: gateway.karl.io/v1alpha1
kind: GatewayRoute
metadata:
  name: claims-calc-remoteapp-route
  namespace: karl-sandbox
spec:
  shellRef:
    name: claims-calc-remoteapp
  gatewayClass: karl.rdpgw.v1
  displayName: RemoteApp RDP route (claims calculator)
  rdp:
    screenMode: 2
    remoteApplicationMode: true
    remoteApplicationProgram: "||CLAIMS_CALC"
    remoteApplicationName: "Claims Calculator"
    remoteApplicationCmdLine: ""
  tokenPolicy:
    ttlSeconds: 600
