package canarymovement

func ReferenceSurface() (map[string]interface{}, error) {
	return referenceSurfaceDoc(), nil
}

func referenceSurfaceDoc() map[string]interface{} {
	candidate := map[string]interface{}{
		"candidateId": "cand-1", "sourceActionId": "act-3", "donorShellId": "d3", "receiverShellId": "r3",
		"resource": "cpu", "amount": "250m", "productionCanaryScope": true, "generalProductionScope": false,
		"allowlisted": true, "selected": true, "blocked": false, "blockerCodes": []interface{}{},
		"evidenceRefs": []interface{}{"artifact://cand-1"}, "claimBoundary": "candidate only",
	}
	return map[string]interface{}{
		"milestone": Milestone, "surfaceVersion": "v1", "canaryExpansionId": "canary-exp-s21-v1",
		"generatedAt": "2026-05-14T19:00:00Z",
		"sourceObservationWindowRef": "configmap://karl-system/hyperdensity-production-observation-window-v1",
		"sourceRealInputTickRef": "configmap://karl-system/hyperdensity-runtime-market-real-inputs-no-apply-v1",
		"sourceProductionCanaryPolicyRef": "configmap://karl-system/hyperdensity-production-canary-policy-v1",
		"controllerMode": "production_canary_only",
		"productionCanaryMovementExpansionEnabled": true, "stableObservationWindowRequired": true,
		"stableObservationWindowObserved": true, "productionCanaryMovementAllowed": true,
		"productionCanaryMovementExecuted": true, "productionCanaryScope": true,
		"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
		"broadProductionMutationExecuted": false,
		"candidateSelectionPassed": true, "allowlistGatePassed": true, "blastRadiusGatePassed": true,
		"sloGatePassed": true, "rollbackGatePassed": true, "killSwitchGatePassed": true,
		"circuitBreakerGatePassed": true, "rateLimitGatePassed": true,
		"executionLeaseCreated": true, "fluidvirtInvocationRecorded": true, "mutationObserved": true,
		"postVerifyPassed": true, "rollbackWindowOpen": true,
		"realizedCompressionRecorded": true, "realizedValueRecorded": true,
		"projectedRealizedSeparated": true, "canaryCloseoutRecorded": true,
		"candidateCount": float64(3), "selectedCanaryCandidateCount": float64(1),
		"executedCanaryMovementCount": float64(1), "blockedCandidateCount": float64(2),
		"rollbackRequiredCount": float64(0), "rollbackExecutedCount": float64(0),
		"realizedMovementCount": float64(1), "realizedMovedIdleValue": float64(200),
		"realizedCompressionDelta": 0.01, "realizedValue": float64(48),
		"projectedMovedIdleValue": float64(1250), "projectedCompressionDelta": 0.03,
		"projectedValueOpportunity": float64(4800),
		"universalGuaranteedSavingsAllowed": false, "universalGuaranteedSavingsClaimed": false,
		"projectedCompressionCountedAsRealized": false, "projectedValueCountedAsRealized": false,
		"estimatedIdleCountedAsMoved": false, "syntheticFleetCountedAsProduction": false,
		"referenceFleetCountedAsProduction": false, "dashboardExecutor": false,
		"fluidvirtPolicyAuthority": false, "fluidvirtControllerAuthority": false,
		"inventoryRuntimeExecutor": false,
		"candidateSelection": map[string]interface{}{
			"candidateSelectionId": "sel-1",
			"sourceObservationWindowRef": "configmap://karl-system/hyperdensity-production-observation-window-v1",
			"candidateCount": float64(3), "selectedCanaryCandidateCount": float64(1), "blockedCandidateCount": float64(2),
			"candidates": []interface{}{
				candidate,
				map[string]interface{}{
					"candidateId": "cand-2", "sourceActionId": "act-1", "donorShellId": "d1", "receiverShellId": "r1",
					"resource": "cpu", "amount": "500m", "productionCanaryScope": false, "generalProductionScope": false,
					"allowlisted": true, "selected": false, "blocked": true, "blockerCodes": []interface{}{"operator_controlled_scope"},
					"evidenceRefs": []interface{}{"artifact://cand-2"}, "claimBoundary": "candidate only",
				},
			},
			"selectionReason": "stable_observation_window_top_canary_candidate",
			"selectionPassed": true,
			"evidenceRefs": []interface{}{"artifact://selection"}, "claimBoundary": "candidate selection only",
		},
		"allowlistGate": map[string]interface{}{
			"allowlistGateId": "al-1", "allowlistSource": "configmap://karl-system/canary-allowlist-v1",
			"allowlistedShells": []interface{}{"d3", "r3"}, "allowlistedNamespaces": []interface{}{"prod-canary"},
			"selectedCandidatesAllowlisted": true, "allowlistGatePassed": true,
			"evidenceRefs": []interface{}{"artifact://allowlist"}, "claimBoundary": "allowlist gate only",
		},
		"blastRadiusGate": map[string]interface{}{
			"blastRadiusGateId": "br-1", "maxMovementCount": float64(1), "maxCpuMillicores": float64(500),
			"maxMemoryMiB": float64(512), "maxTenantCount": float64(1),
			"requestedMovementCount": float64(1), "requestedCpuMillicores": float64(250),
			"requestedMemoryMiB": float64(0), "requestedTenantCount": float64(1),
			"blastRadiusExceeded": false, "blastRadiusGatePassed": true,
			"evidenceRefs": []interface{}{"artifact://blast-radius"}, "claimBoundary": "blast radius gate only",
		},
		"executionLease": map[string]interface{}{
			"leaseId": "lease-1", "candidateId": "cand-1", "donorShellId": "d3", "receiverShellId": "r3",
			"resource": "cpu", "amount": "250m", "ttlSeconds": float64(300), "state": "active",
			"createdAt": "2026-05-14T18:58:00Z", "expiresAt": "2026-05-14T19:03:00Z",
			"productionCanaryScope": true, "generalProductionScope": false,
			"evidenceRefs": []interface{}{"artifact://lease"}, "claimBoundary": "execution lease only",
		},
		"applyRequest": map[string]interface{}{
			"applyRequestId": "req-1", "candidateId": "cand-1", "leaseId": "lease-1",
			"donorShellId": "d3", "receiverShellId": "r3", "resource": "cpu", "amount": "250m",
			"requestedAt": "2026-05-14T18:58:30Z", "requestedBy": "Karl-Hyperdensity", "actuator": "FluidVirt",
			"productionCanaryScope": true, "generalProductionScope": false,
			"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
			"evidenceRefs": []interface{}{"artifact://apply-req"}, "claimBoundary": "apply request only",
		},
		"fluidvirtInvocation": map[string]interface{}{
			"invocationId": "inv-1", "applyRequestId": "req-1", "actuator": "FluidVirt",
			"mutationFamily": "cpu_entitlement", "invokedAt": "2026-05-14T18:58:35Z",
			"requestAccepted": true, "mutationExecuted": true,
			"productionCanaryScope": true, "generalProductionScope": false,
			"evidenceRefs": []interface{}{"artifact://invocation"}, "claimBoundary": "FluidVirt invocation only",
		},
		"mutationObservation": map[string]interface{}{
			"mutationObservationId": "mut-1", "invocationId": "inv-1",
			"donorShellId": "d3", "receiverShellId": "r3", "resource": "cpu",
			"requestedAmount": "250m", "appliedAmount": "250m",
			"mutationObserved": true, "mutationMatchesPlan": true, "identityPreserved": true,
			"rebootUsed": false, "recreateUsed": false, "rolloutUsed": false, "migrationUsed": false,
			"cgroupObserved": true, "libvirtObserved": true, "qgaObserved": false,
			"observedAt": "2026-05-14T18:58:50Z",
			"evidenceRefs": []interface{}{"artifact://mutation"}, "claimBoundary": "mutation observation only",
		},
		"postVerifyResult": map[string]interface{}{
			"postVerifyId": "pv-1", "mutationObservationId": "mut-1", "verifyStatus": "passed",
			"runtimeDeltaVerified": true, "guestDeltaVerified": true, "sloGuardStatus": "passed",
			"donorHealthStatus": "preserved", "receiverHealthStatus": "preserved",
			"rollbackReady": true, "rollbackRequired": false,
			"mutationKept": true, "mutationRolledBack": false,
			"verifiedAt": "2026-05-14T18:59:15Z",
			"evidenceRefs": []interface{}{"artifact://post-verify"}, "claimBoundary": "post verify only",
		},
		"rollbackWindow": map[string]interface{}{
			"rollbackWindowId": "rb-1", "mutationObservationId": "mut-1", "state": "open",
			"openedAt": "2026-05-14T18:59:15Z", "expiresAt": "2026-05-14T19:29:15Z",
			"rollbackAvailable": true, "rollbackTested": true, "rollbackExecuted": false, "rollbackPassed": false,
			"evidenceRefs": []interface{}{"artifact://rollback-window"}, "claimBoundary": "rollback window only",
		},
		"realizedCompressionRecord": map[string]interface{}{
			"compressionRecordId": "rcr-1", "mutationObservationId": "mut-1",
			"sourceObservationWindowRef": "configmap://karl-system/hyperdensity-production-observation-window-v1",
			"realizedMovementCount": float64(1), "realizedMovedIdleValue": float64(200),
			"realizedCompressionDelta": 0.01, "projectedCompressionExcluded": true,
			"estimatedValueExcluded": true, "movementEvidencePresent": true,
			"evidenceRefs": []interface{}{"artifact://compression-record"}, "claimBoundary": "realized compression only",
		},
		"realizedValueRecord": map[string]interface{}{
			"valueRecordId": "rvr-1", "mutationObservationId": "mut-1", "resource": "cpu", "amount": "250m",
			"durationSeconds": float64(3600), "unitPrice": 0.048, "grossValue": float64(48),
			"controlCost": float64(2), "riskCost": float64(1), "netRealizedValue": float64(45),
			"guaranteedEligible": true, "guaranteeScope": "scoped_eligible_canary_only",
			"evidenceRefs": []interface{}{"artifact://value-record"}, "claimBoundary": "realized value only",
		},
		"projectedRealizedSeparation": map[string]interface{}{
			"separationId": "sep-1", "projectedMovedIdleValue": float64(1250),
			"projectedCompressionDelta": 0.03, "projectedValueOpportunity": float64(4800),
			"realizedMovedIdleValue": float64(200), "realizedCompressionDelta": 0.01, "realizedValue": float64(48),
			"projectedCompressionCountedAsRealized": false, "projectedValueCountedAsRealized": false,
			"estimatedIdleCountedAsMoved": false, "syntheticValueExcluded": true, "referenceValueExcluded": true,
			"separationPassed": true,
			"evidenceRefs": []interface{}{"artifact://separation"}, "claimBoundary": "projected/realized separation only",
		},
		"canaryCloseout": map[string]interface{}{
			"closeoutId": "close-1", "canaryExpansionId": "canary-exp-s21-v1", "closeoutStatus": "passed",
			"promotedToGeneralProduction": false, "nextAllowedState": "production_canary_only",
			"rollbackWindowClosed": false, "auditComplete": true,
			"evidenceRefs": []interface{}{"artifact://closeout"}, "claimBoundary": "canary closeout only",
		},
		"auditEvents": []interface{}{
			map[string]interface{}{
				"auditEventId": "aud-1", "eventType": "candidate_selected", "occurredAt": "2026-05-14T18:57:00Z",
				"sourceComponent": "Karl-Hyperdensity", "actorType": "controller",
				"summary": "canary candidate selected from stable observation window",
				"evidenceRefs": []interface{}{"artifact://aud-1"}, "claimBoundary": "audit only",
			},
			map[string]interface{}{
				"auditEventId": "aud-2", "eventType": "canary_closed", "occurredAt": "2026-05-14T19:00:00Z",
				"sourceComponent": "Karl-Hyperdensity", "actorType": "controller",
				"summary": "canary movement completed, remains production_canary_only",
				"evidenceRefs": []interface{}{"artifact://aud-2"}, "claimBoundary": "audit only",
			},
		},
		"sourceOfTruth": map[string]interface{}{
			"runtimeMutation": "FluidVirt", "marketDecision": "Karl-Hyperdensity",
			"identitySignals": "Karl-Inventory", "operatorUI": "Karl-Dashboard (projection only)",
		},
		"safetyInvariants": []interface{}{
			"bounded canary movement only", "general production auto disabled",
			"projected value never counted as realized",
		},
		"claimBoundaries": []interface{}{
			"canary movement evidence from mutation and post-verify only",
			"no broad production mutation claim", "no production_auto_with_policy",
		},
		"blockers": []interface{}{},
		"warnings": []interface{}{},
		"referenceScenarios": []interface{}{
			map[string]interface{}{"scenarioId": "success", "productionCanaryMovementExecuted": true, "promotedToGeneralProduction": false},
			map[string]interface{}{"scenarioId": "no_stable_window", "stableObservationWindowObserved": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "not_allowlisted", "allowlistGatePassed": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "blast_radius_exceeded", "blastRadiusGatePassed": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "slo_failed", "sloGatePassed": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "rollback_not_ready", "rollbackGatePassed": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "kill_switch", "killSwitchGatePassed": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "circuit_breaker", "circuitBreakerGatePassed": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "non_canary_movement", "productionCanaryScope": false, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "projected_realized", "projectedCompressionCountedAsRealized": true, "productionCanaryMovementExecuted": false},
			map[string]interface{}{"scenarioId": "dashboard_executor", "dashboardExecutor": true, "productionCanaryMovementExecuted": false},
		},
	}
}
