package realmarkettick

func ReferenceSurface() (map[string]interface{}, error) {
	return referenceSurfaceDoc(), nil
}

func referenceSurfaceDoc() map[string]interface{} {
	pw := map[string]interface{}{
		"pairingWindowId": "pair-1", "fullPairSpace": float64(100), "evaluatedPairCount": float64(25),
		"avoidedPairCount": float64(75), "avoidancePercent": float64(75), "topKDonors": float64(5),
		"topKReceivers": float64(5), "noFullNxNPairing": true,
		"evaluatedPairs": []interface{}{map[string]interface{}{"donorShellId": "d1", "receiverShellId": "r1"}},
		"skippedPairsSummary": "top-K bounded", "evidenceRefs": []interface{}{"artifact://pairing"}, "claimBoundary": "pairing window only",
	}
	return map[string]interface{}{
		"milestone": Milestone, "surfaceVersion": "v1", "realMarketTickId": "real-tick-s19-v1",
		"generatedAt": "2026-05-14T18:00:00Z",
		"sourceSmokeTickRef": "configmap://karl-system/hyperdensity-controller-runtime-smoke-tick-v1",
		"sourceShellRegistryRef": "configmap://karl-system/shell-registry-v1",
		"sourceInventorySignalsRef": "configmap://karl-system/inventory-signals-v1",
		"sourceIdleMeasurementRef": "configmap://karl-system/fluidvirt-idle-measurement-v1",
		"sourcePressureSignalsRef": "configmap://karl-system/pressure-signals-v1",
		"sourceSloReadinessRef": "configmap://karl-system/slo-readiness-v1",
		"sourceRollbackReadinessRef": "configmap://karl-system/rollback-readiness-v1",
		"sourceRiskSignalsRef": "configmap://karl-system/risk-signals-v1",
		"controllerMode": "production_canary_only",
		"realInputMarketTickEnabled": true, "productionObservationMode": true, "noApplyMode": true,
		"realInputMarketTickExecuted": true, "realInputMarketTickPassed": true,
		"realShellInputsObserved": true, "realIdleSignalsObserved": true, "realPressureSignalsObserved": true,
		"realSloReadinessObserved": true, "realRollbackReadinessObserved": true, "realRiskSignalsObserved": true,
		"inputFreshnessValidated": true, "staleInputsInvalidated": true,
		"realInputDonorIndexGenerated": true, "realInputReceiverIndexGenerated": true,
		"boundedPairingVerified": true, "noFullNxNPairing": true,
		"noApplyActionSlateGenerated": true, "noApplyFuturesGenerated": true,
		"observationMetricsEmitted": true, "observationEventsEmitted": true, "dashboardProjectionUpdated": true,
		"productionMovementExecuted": false, "broadProductionMutationExecuted": false,
		"fullPairSpace": float64(100), "evaluatedPairCount": float64(25), "avoidedPairCount": float64(75),
		"topKDonors": float64(5), "topKReceivers": float64(5),
		"observedShellCount": float64(12), "productionObservedShellCount": float64(7),
		"referenceOnlyShellCount": float64(2), "syntheticShadowShellCount": float64(1),
		"eligibleDonorCount": float64(4), "pressureReceiverCount": float64(3),
		"staleInputCount": float64(1), "invalidatedInputCount": float64(1),
		"generatedActionCount": float64(3), "generatedFutureCount": float64(2),
		"operatorControlledCandidateCount": float64(1), "sandboxNonprodCandidateCount": float64(1),
		"productionCanaryCandidateCount": float64(1), "remediationOnlyCount": float64(0), "blockedActionCount": float64(0),
		"currentIdleCompressionRate": 0.12, "projectedIdleCompressionRate": 0.18, "realizedIdleCompressionRate": 0.0,
		"projectedMovedIdleValue": float64(1200), "realizedMovedIdleValue": float64(0),
		"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
		"universalGuaranteedSavingsAllowed": false, "universalGuaranteedSavingsClaimed": false,
		"estimatedIdleCountedAsMoved": false, "projectedCompressionCountedAsRealized": false,
		"syntheticFleetCountedAsProduction": false, "referenceFleetCountedAsProduction": false,
		"dashboardExecutor": false, "fluidvirtPolicyAuthority": false, "fluidvirtTickAuthority": false,
		"inventoryRuntimeExecutor": false,
		"realShellInputSnapshot": map[string]interface{}{
			"snapshotId": "snap-1", "collectedAt": "2026-05-14T17:59:00Z", "source": "shell-registry+inventory+k8s",
			"observedShellCount": float64(12), "productionObservedShellCount": float64(7),
			"canaryObservedShellCount": float64(2), "sandboxNonprodObservedShellCount": float64(3),
			"referenceOnlyShellCount": float64(2), "syntheticShadowShellCount": float64(1), "staleShellCount": float64(1),
			"shells": []interface{}{
				map[string]interface{}{
					"shellId": "sh-1", "shellKind": "deployment", "namespace": "prod", "workloadName": "api",
					"identityStable": true, "sourceKind": "shell_registry", "observedAt": "2026-05-14T17:58:30Z",
					"freshnessSeconds": float64(30), "productionEvidence": true, "referenceOnly": false,
					"syntheticShadow": false, "blocked": false, "protected": false,
					"evidenceRefs": []interface{}{"artifact://sh-1"}, "claimBoundary": "shell only",
				},
			},
			"evidenceRefs": []interface{}{"artifact://snapshot"}, "claimBoundary": "shell snapshot only",
		},
		"shellInputSourceMap": map[string]interface{}{
			"sourceMapId": "src-1", "shellRegistrySource": "configmap://karl-system/shell-registry-v1",
			"inventorySignalSource": "configmap://karl-system/inventory-signals-v1",
			"kubernetesObjectSource": "k8s://deployments", "fluidvirtMeasurementSource": "configmap://karl-system/fluidvirt-measurement-v1",
			"sloSource": "configmap://karl-system/slo-readiness-v1", "rollbackSource": "configmap://karl-system/rollback-readiness-v1",
			"riskSource": "configmap://karl-system/risk-signals-v1", "sourceFreshnessSeconds": float64(60),
			"sourceOfTruth": map[string]interface{}{"identity": "Karl-Inventory", "measurement": "FluidVirt"},
			"evidenceRefs": []interface{}{"artifact://source-map"}, "claimBoundary": "source map only",
		},
		"observedIdleSignals": map[string]interface{}{
			"idleSignalSetId": "idle-1", "collectedAt": "2026-05-14T17:59:00Z",
			"signalCount": float64(6), "eligibleIdleSignalCount": float64(5), "staleIdleSignalCount": float64(1),
			"idleSignals": []interface{}{
				map[string]interface{}{
					"shellId": "sh-1", "resource": "cpu", "idleAmount": "500m", "idleValue": float64(400),
					"observedAt": "2026-05-14T17:58:45Z", "freshnessSeconds": float64(15), "eligible": true, "stale": false,
					"evidenceRefs": []interface{}{"artifact://idle-1"}, "claimBoundary": "idle signal only",
				},
			},
			"evidenceRefs": []interface{}{"artifact://idle"}, "claimBoundary": "idle signals only",
		},
		"observedPressureSignals": map[string]interface{}{
			"pressureSignalSetId": "press-1", "collectedAt": "2026-05-14T17:59:00Z",
			"signalCount": float64(5), "eligiblePressureSignalCount": float64(4), "stalePressureSignalCount": float64(1),
			"pressureSignals": []interface{}{
				map[string]interface{}{
					"shellId": "sh-2", "resource": "memory", "pressureClass": "high", "requestedAmount": "256Mi",
					"observedAt": "2026-05-14T17:58:50Z", "freshnessSeconds": float64(10), "eligible": true, "stale": false,
					"evidenceRefs": []interface{}{"artifact://press-1"}, "claimBoundary": "pressure signal only",
				},
			},
			"evidenceRefs": []interface{}{"artifact://pressure"}, "claimBoundary": "pressure signals only",
		},
		"observedSloReadiness": map[string]interface{}{
			"sloReadinessSetId": "slo-1", "collectedAt": "2026-05-14T17:59:00Z",
			"readyCount": float64(5), "missingCount": float64(1), "staleCount": float64(0),
			"entries": []interface{}{map[string]interface{}{"shellId": "sh-1", "ready": true}},
			"evidenceRefs": []interface{}{"artifact://slo"}, "claimBoundary": "slo readiness only",
		},
		"observedRollbackReadiness": map[string]interface{}{
			"rollbackReadinessSetId": "rb-1", "collectedAt": "2026-05-14T17:59:00Z",
			"readyCount": float64(5), "missingCount": float64(1), "staleCount": float64(0),
			"entries": []interface{}{map[string]interface{}{"shellId": "sh-1", "ready": true}},
			"evidenceRefs": []interface{}{"artifact://rollback"}, "claimBoundary": "rollback readiness only",
		},
		"observedRiskSignals": map[string]interface{}{
			"riskSignalSetId": "risk-1", "collectedAt": "2026-05-14T17:59:00Z",
			"lowRiskCount": float64(4), "mediumRiskCount": float64(2), "highRiskCount": float64(0), "staleCount": float64(0),
			"entries": []interface{}{map[string]interface{}{"shellId": "sh-1", "riskClass": "low"}},
			"evidenceRefs": []interface{}{"artifact://risk"}, "claimBoundary": "risk signals only",
		},
		"inputFreshnessValidation": map[string]interface{}{
			"freshnessValidationId": "fresh-1", "evaluatedAt": "2026-05-14T17:59:05Z",
			"maxAllowedFreshnessSeconds": float64(120), "shellInputsFresh": true, "idleSignalsFresh": true,
			"pressureSignalsFresh": true, "sloReadinessFresh": true, "rollbackReadinessFresh": true, "riskSignalsFresh": true,
			"inputFreshnessValidated": true, "staleInputCount": float64(1),
			"evidenceRefs": []interface{}{"artifact://freshness"}, "claimBoundary": "freshness validation only",
		},
		"staleInputInvalidations": []interface{}{
			map[string]interface{}{
				"invalidationId": "inv-1", "inputType": "idle_signal", "inputId": "idle-stale-1", "shellId": "sh-3",
				"reason": "freshness_exceeded", "invalidatedAt": "2026-05-14T17:59:05Z", "replacementAvailable": false,
				"evidenceRefs": []interface{}{"artifact://inv-1"}, "claimBoundary": "stale invalidation only",
			},
		},
		"donorIndex": map[string]interface{}{
			"donorIndexId": "donor-1", "generatedAt": "2026-05-14T17:59:10Z",
			"donorCount": float64(4), "eligibleDonorCount": float64(3), "excludedDonorCount": float64(1), "topK": float64(5),
			"donors": []interface{}{map[string]interface{}{"shellId": "d1", "idleValue": float64(400)}},
			"excludedDonors": []interface{}{map[string]interface{}{"shellId": "d-x", "reason": "blocked"}},
			"evidenceRefs": []interface{}{"artifact://donor-index"}, "claimBoundary": "donor index only",
		},
		"receiverIndex": map[string]interface{}{
			"receiverIndexId": "recv-1", "generatedAt": "2026-05-14T17:59:10Z",
			"receiverCount": float64(3), "eligibleReceiverCount": float64(3), "excludedReceiverCount": float64(0), "topK": float64(5),
			"receivers": []interface{}{map[string]interface{}{"shellId": "r1", "pressureClass": "high"}},
			"excludedReceivers": []interface{}{},
			"evidenceRefs": []interface{}{"artifact://receiver-index"}, "claimBoundary": "receiver index only",
		},
		"pairingWindow": pw,
		"generatedActions": []interface{}{
			map[string]interface{}{
				"actionId": "act-1", "donorShellId": "d1", "receiverShellId": "r1", "resource": "cpu", "amount": "500m",
				"executionScopeRecommendation": "operator_controlled_candidate", "productionScope": false, "productionCanaryScope": false,
				"sandboxNonprodScope": false, "operatorControlledScope": true, "selectedForExecution": false,
				"noApplyReason": "production_observation_mode", "expectedMovedIdleValue": float64(400), "expectedCompressionGain": 0.02,
				"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
				"evidenceRefs": []interface{}{"artifact://act-1"}, "claimBoundary": "generated action only",
			},
			map[string]interface{}{
				"actionId": "act-2", "donorShellId": "d2", "receiverShellId": "r2", "resource": "memory", "amount": "256Mi",
				"executionScopeRecommendation": "sandbox_nonprod_candidate", "productionScope": false, "productionCanaryScope": false,
				"sandboxNonprodScope": true, "operatorControlledScope": false, "selectedForExecution": false,
				"noApplyReason": "production_observation_mode", "expectedMovedIdleValue": float64(250), "expectedCompressionGain": 0.01,
				"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
				"evidenceRefs": []interface{}{"artifact://act-2"}, "claimBoundary": "generated action only",
			},
			map[string]interface{}{
				"actionId": "act-3", "donorShellId": "d3", "receiverShellId": "r3", "resource": "cpu", "amount": "250m",
				"executionScopeRecommendation": "production_canary_candidate", "productionScope": false, "productionCanaryScope": true,
				"sandboxNonprodScope": false, "operatorControlledScope": false, "selectedForExecution": false,
				"noApplyReason": "production_observation_mode", "expectedMovedIdleValue": float64(200), "expectedCompressionGain": 0.01,
				"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
				"evidenceRefs": []interface{}{"artifact://act-3"}, "claimBoundary": "generated action only",
			},
		},
		"generatedFutures": []interface{}{
			map[string]interface{}{
				"futureId": "fut-1", "donorShellId": "d1", "receiverShellId": "r2", "resource": "memory", "amount": "512Mi",
				"horizonSeconds": float64(3600), "confidence": 0.72, "pressureProbability": 0.6, "donorAvailabilityProbability": 0.8,
				"triggerCondition": "pressure_above_threshold", "expiration": "2026-05-14T22:00:00Z", "invalidationReasons": []interface{}{},
				"executionScopeRecommendation": "production_canary_candidate", "expectedMovedIdleValue": float64(300), "expectedCompressionGain": 0.01,
				"evidenceRefs": []interface{}{"artifact://fut-1"}, "claimBoundary": "generated future only",
			},
			map[string]interface{}{
				"futureId": "fut-2", "donorShellId": "d2", "receiverShellId": "r1", "resource": "cpu", "amount": "300m",
				"horizonSeconds": float64(7200), "confidence": 0.65, "pressureProbability": 0.55, "donorAvailabilityProbability": 0.75,
				"triggerCondition": "idle_above_threshold", "expiration": "2026-05-15T00:00:00Z", "invalidationReasons": []interface{}{},
				"executionScopeRecommendation": "operator_controlled_candidate", "expectedMovedIdleValue": float64(180), "expectedCompressionGain": 0.008,
				"evidenceRefs": []interface{}{"artifact://fut-2"}, "claimBoundary": "generated future only",
			},
		},
		"observationMetrics": map[string]interface{}{
			"metricsId": "metrics-1", "emittedAt": "2026-05-14T17:59:45Z",
			"tickTotal": float64(1), "tickSuccessTotal": float64(1), "tickFailureTotal": float64(0),
			"observedShellCountGauge": float64(12), "eligibleDonorCountGauge": float64(4), "pressureReceiverCountGauge": float64(3),
			"staleInputCountGauge": float64(1), "generatedActionsGauge": float64(3), "generatedFuturesGauge": float64(2),
			"evaluatedPairCountGauge": float64(25), "avoidedPairCountGauge": float64(75),
			"currentIdleCompressionRateGauge": 0.12, "projectedIdleCompressionRateGauge": 0.18, "realizedIdleCompressionRateGauge": 0.0,
			"generalProductionAutoEnabledGauge": float64(0), "productionAutoWithPolicyEnabledGauge": float64(0),
			"evidenceRefs": []interface{}{"artifact://metrics"}, "claimBoundary": "observation metrics only",
		},
		"observationEvents": []interface{}{
			map[string]interface{}{
				"eventId": "evt-1", "eventType": "real_input_tick_started", "occurredAt": "2026-05-14T17:59:00Z",
				"sourceComponent": "Karl-Hyperdensity", "involvedObjectKind": "ConfigMap",
				"involvedObjectName": "hyperdensity-runtime-market-real-inputs-no-apply-v1",
				"summary": "real-input observation tick started", "evidenceRefs": []interface{}{"artifact://evt-1"}, "claimBoundary": "observation event only",
			},
			map[string]interface{}{
				"eventId": "evt-2", "eventType": "observation_tick_passed", "occurredAt": "2026-05-14T17:59:45Z",
				"sourceComponent": "Karl-Hyperdensity", "involvedObjectKind": "ConfigMap",
				"involvedObjectName": "hyperdensity-runtime-market-real-inputs-no-apply-v1",
				"summary": "real-input no-apply tick passed", "evidenceRefs": []interface{}{"artifact://evt-2"}, "claimBoundary": "observation event only",
			},
		},
		"noApplySafetyBoundary": map[string]interface{}{
			"safetyBoundaryId": "safety-1", "productionMovementExecuted": false, "broadProductionMutationExecuted": false,
			"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false, "selectedProductionExecution": false,
			"dashboardExecutor": false, "fluidvirtTickAuthority": false, "rawRuntimeControlsExposed": false, "inventoryRuntimeExecutor": false,
			"evidenceRefs": []interface{}{"artifact://safety"}, "claimBoundary": "no-apply safety boundary only",
		},
		"sourceOfTruth": map[string]interface{}{
			"runtimeMutation": "FluidVirt", "marketDecision": "Karl-Hyperdensity",
			"identitySignals": "Karl-Inventory", "operatorUI": "Karl-Dashboard (projection only)",
		},
		"safetyInvariants": []interface{}{
			"no production movement in observation tick", "bounded top-K pairing only", "dashboard projection read-only",
		},
		"claimBoundaries": []interface{}{
			"real-input market tick generates candidates only", "no broad production mutation claim",
			"projected compression is not realized without movement evidence",
		},
		"blockers": []interface{}{},
		"warnings": []interface{}{},
		"referenceScenarios": []interface{}{
			map[string]interface{}{"scenarioId": "success", "realInputMarketTickPassed": true, "productionMovementExecuted": false},
			map[string]interface{}{"scenarioId": "missing_shell_input", "realShellInputsObserved": false, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "missing_idle_signals", "realIdleSignalsObserved": false, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "missing_pressure_signals", "realPressureSignalsObserved": false, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "stale_not_invalidated", "staleInputsInvalidated": false, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "full_nxn_attempted", "noFullNxNPairing": false, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "forbidden_auto_scope", "executionScopeRecommendation": "general_production_auto", "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "action_selected", "selectedForExecution": true, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "synthetic_reference_prod", "syntheticFleetCountedAsProduction": true, "realInputMarketTickPassed": false},
			map[string]interface{}{"scenarioId": "projected_realized", "projectedCompressionCountedAsRealized": true, "realInputMarketTickPassed": false},
		},
	}
}
