package contracts

const (
	LinuxShellComplianceV1ID           = "hyperdensity_linux_shell_compliance_v1"
	ResourceEquilibriumV1ID            = "hyperdensity_resource_equilibrium_v1"
	FleetEquilibriumOnboardingV1ID     = "hyperdensity_fleet_equilibrium_onboarding_v1"
	ShellFactoryV1ID                   = "hyperdensity_shell_factory_v1"
	ShellClaimV1ID                     = "hyperdensity_shell_claim_v1"
	ShellClaimTemplateProfilePackV1ID  = "hyperdensity_shell_claim_templates_profile_pack_v1"
	ReleaseSupportMatrixV1ID           = "hyperdensity_release_support_matrix_v1"
	EvidenceBundleDemoScenarioPackV1ID = "hyperdensity_evidence_bundle_demo_scenario_pack_v1"
	LiveResourceAuthorityV1ID          = "hyperdensity_live_resource_authority_v1"
	ActionSlateV1ID                    = "hyperdensity_action_slate_v1"
	GuardedAutoSandboxV1ID             = "hyperdensity_guarded_auto_sandbox_v1"
	AutoRollbackControllerV1ID         = "hyperdensity_auto_rollback_controller_v1"
	BlastRadiusPolicyV1ID              = "hyperdensity_blast_radius_policy_v1"
	ProductionKernelBoundaryV1ID       = "hyperdensity_production_kernel_boundary_v1"
	ClaimPolicyV2ID                    = "hyperdensity_claim_policy_v2"
	ShellPassportV1ID                  = "hyperdensity_shell_passport_v1"
	ShellPassportFactoryV1ID           = "hyperdensity_shell_passport_factory_v1"
	ShellRegistryV1ID                  = "hyperdensity_shell_registry_v1"
	ShellEnrollmentResultV1ID          = "hyperdensity_shell_enrollment_result_v1"
	ShellCapabilityEvidenceV1ID        = "hyperdensity_shell_capability_evidence_v1"
	ResourceLeaseActionSlateReadinessV1ID = "hyperdensity_resource_lease_action_slate_readiness_v1"
	DonorIndexV1ID                   = "hyperdensity_donor_index_v1"
	ReceiverIndexV1ID                = "hyperdensity_receiver_index_v1"
	ResourceLeaseCandidateV1ID       = "hyperdensity_resource_lease_candidate_v1"
	ActionSlateReadinessV1ID         = "hyperdensity_action_slate_readiness_v1"
	ActionSlateEntryV1ID             = "hyperdensity_action_slate_entry_v1"
	ActionDryrunReadinessV1ID        = "hyperdensity_action_dryrun_readiness_v1"
	RollbackReadinessV1ID            = "hyperdensity_rollback_readiness_v1"
	SloPrecheckV1ID                  = "hyperdensity_slo_precheck_v1"
	RiskAssessmentV1ID               = "hyperdensity_risk_assessment_v1"
	RuntimeMutationResultV1ID          = "hyperdensity_runtime_mutation_result_v1"
	ResourceLeaseV1ID                  = "hyperdensity_resource_lease_v1"
)
