package canarycohort

func ReferenceSurface() (map[string]interface{}, error) {
	return referenceSurfaceDoc(), nil
}

func referenceSurfaceDoc() map[string]interface{} {
	candidates := []interface{}{
		map[string]interface{}{
			"candidateId": "cand-1", "sourceActionId": "act-3", "donorShellId": "d3", "receiverShellId": "r3",
			"resource": "cpu", "amount": "250m", "productionCanaryScope": true, "generalProductionScope": false,
			"allowlisted": true, "selected": true, "blocked": false, "blockerCodes": []interface{}{},
			"evidenceRefs": []interface{}{"artifact://cand-1"}, "claimBoundary": "candidate only",
		},
		map[string]interface{}{
			"candidateId": "cand-2", "sourceActionId": "act-4", "donorShellId": "d4", "receiverShellId": "r4",
			"resource": "memory", "amount": "256Mi", "productionCanaryScope": true, "generalProductionScope": false,
			"allowlisted": true, "selected": true, "blocked": false, "blockerCodes": []interface{}{},
			"evidenceRefs": []interface{}{"artifact://cand-2"}, "claimBoundary": "candidate only",
		},
		map[string]interface{}{
			"candidateId": "cand-3", "sourceActionId": "act-1", "donorShellId": "d1", "receiverShellId": "r1",
			"resource": "cpu", "amount": "500m", "productionCanaryScope": false, "generalProductionScope": false,
			"allowlisted": true, "selected": false, "blocked": true, "blockerCodes": []interface{}{"operator_controlled_scope"},
			"evidenceRefs": []interface{}{"artifact://cand-3"}, "claimBoundary": "candidate only",
		},
	}
	leases := []interface{}{
		map[string]interface{}{
			"leaseId": "lease-1", "candidateId": "cand-1", "donorShellId": "d3", "receiverShellId": "r3",
			"resource": "cpu", "amount": "250m", "ttlSeconds": float64(300), "state": "active",
			"createdAt": "2026-05-14T19:30:00Z", "expiresAt": "2026-05-14T19:35:00Z",
			"productionCanaryScope": true, "generalProductionScope": false,
			"evidenceRefs": []interface{}{"artifact://lease-1"}, "claimBoundary": "execution lease only",
		},
		map[string]interface{}{
			"leaseId": "lease-2", "candidateId": "cand-2", "donorShellId": "d4", "receiverShellId": "r4",
			"resource": "memory", "amount": "256Mi", "ttlSeconds": float64(300), "state": "active",
			"createdAt": "2026-05-14T19:36:00Z", "expiresAt": "2026-05-14T19:41:00Z",
			"productionCanaryScope": true, "generalProductionScope": false,
			"evidenceRefs": []interface{}{"artifact://lease-2"}, "claimBoundary": "execution lease only",
		},
	}
	invocations := []interface{}{
		map[string]interface{}{
			"invocationId": "inv-1", "applyRequestId": "req-1", "actuator": "FluidVirt",
			"mutationFamily": "cpu_entitlement", "invokedAt": "2026-05-14T19:30:30Z",
			"requestAccepted": true, "mutationExecuted": true,
			"productionCanaryScope": true, "generalProductionScope": false,
			"evidenceRefs": []interface{}{"artifact://inv-1"}, "claimBoundary": "FluidVirt invocation only",
		},
		map[string]interface{}{
			"invocationId": "inv-2", "applyRequestId": "req-2", "actuator": "FluidVirt",
			"mutationFamily": "memory_envelope", "invokedAt": "2026-05-14T19:36:30Z",
			"requestAccepted": true, "mutationExecuted": true,
			"productionCanaryScope": true, "generalProductionScope": false,
			"evidenceRefs": []interface{}{"artifact://inv-2"}, "claimBoundary": "FluidVirt invocation only",
		},
	}
	mutations := []interface{}{
		map[string]interface{}{
			"mutationObservationId": "mut-1", "invocationId": "inv-1",
			"donorShellId": "d3", "receiverShellId": "r3", "resource": "cpu",
			"requestedAmount": "250m", "appliedAmount": "250m",
			"mutationObserved": true, "mutationMatchesPlan": true, "identityPreserved": true,
			"rebootUsed": false, "recreateUsed": false, "rolloutUsed": false, "migrationUsed": false,
			"cgroupObserved": true, "libvirtObserved": true, "qgaObserved": false,
			"observedAt": "2026-05-14T19:30:50Z",
			"evidenceRefs": []interface{}{"artifact://mut-1"}, "claimBoundary": "mutation observation only",
		},
		map[string]interface{}{
			"mutationObservationId": "mut-2", "invocationId": "inv-2",
			"donorShellId": "d4", "receiverShellId": "r4", "resource": "memory",
			"requestedAmount": "256Mi", "appliedAmount": "256Mi",
			"mutationObserved": true, "mutationMatchesPlan": true, "identityPreserved": true,
			"rebootUsed": false, "recreateUsed": false, "rolloutUsed": false, "migrationUsed": false,
			"cgroupObserved": true, "libvirtObserved": true, "qgaObserved": false,
			"observedAt": "2026-05-14T19:36:50Z",
			"evidenceRefs": []interface{}{"artifact://mut-2"}, "claimBoundary": "mutation observation only",
		},
	}
	postVerifies := []interface{}{
		map[string]interface{}{
			"postVerifyId": "pv-1", "mutationObservationId": "mut-1", "verifyStatus": "passed",
			"runtimeDeltaVerified": true, "guestDeltaVerified": true, "sloGuardStatus": "passed",
			"donorHealthStatus": "preserved", "receiverHealthStatus": "preserved",
			"rollbackReady": true, "rollbackRequired": false,
			"mutationKept": true, "mutationRolledBack": false,
			"verifiedAt": "2026-05-14T19:31:15Z",
			"evidenceRefs": []interface{}{"artifact://pv-1"}, "claimBoundary": "post verify only",
		},
		map[string]interface{}{
			"postVerifyId": "pv-2", "mutationObservationId": "mut-2", "verifyStatus": "passed",
			"runtimeDeltaVerified": true, "guestDeltaVerified": true, "sloGuardStatus": "passed",
			"donorHealthStatus": "preserved", "receiverHealthStatus": "preserved",
			"rollbackReady": true, "rollbackRequired": false,
			"mutationKept": true, "mutationRolledBack": false,
			"verifiedAt": "2026-05-14T19:37:15Z",
			"evidenceRefs": []interface{}{"artifact://pv-2"}, "claimBoundary": "post verify only",
		},
	}
	rollbackWindows := []interface{}{
		map[string]interface{}{
			"rollbackWindowId": "rb-1", "mutationObservationId": "mut-1", "state": "open",
			"openedAt": "2026-05-14T19:31:15Z", "expiresAt": "2026-05-14T20:01:15Z",
			"rollbackAvailable": true, "rollbackTested": true, "rollbackExecuted": false, "rollbackPassed": false,
			"evidenceRefs": []interface{}{"artifact://rb-1"}, "claimBoundary": "rollback window only",
		},
		map[string]interface{}{
			"rollbackWindowId": "rb-2", "mutationObservationId": "mut-2", "state": "open",
			"openedAt": "2026-05-14T19:37:15Z", "expiresAt": "2026-05-14T20:07:15Z",
			"rollbackAvailable": true, "rollbackTested": true, "rollbackExecuted": false, "rollbackPassed": false,
			"evidenceRefs": []interface{}{"artifact://rb-2"}, "claimBoundary": "rollback window only",
		},
	}
	return map[string]interface{}{
		"milestone": Milestone, "surfaceVersion": "v1", "canaryCohortExpansionId": "cohort-exp-s22-v1",
		"generatedAt": "2026-05-14T19:40:00Z",
		"sourceObservationWindowRef": "configmap://karl-system/hyperdensity-production-observation-window-v1",
		"sourcePriorCanaryMovementRef": "configmap://karl-system/hyperdensity-production-canary-movement-expansion-v1",
		"sourceProductionCanaryPolicyRef": "configmap://karl-system/hyperdensity-production-canary-policy-v1",
		"controllerMode": "production_canary_only",
		"productionCanaryCohortExpansionEnabled": true, "stableObservationWindowObserved": true,
		"priorCanaryMovementEvidenceObserved": true, "productionCanaryCohortAllowed": true,
		"productionCanaryCohortExecuted": true, "productionCanaryScope": true,
		"generalProductionAutoAllowed": false, "productionAutoWithPolicy": false,
		"productionAutoWithPolicyEnabled": false, "productionAutoWithPolicyActivated": false,
		"broadProductionMutationExecuted": false,
		"candidateSelectionPassed": true, "allowlistGatePassed": true, "blastRadiusGatePassed": true,
		"sloGatePassed": true, "rollbackGatePassed": true, "killSwitchGatePassed": true,
		"circuitBreakerGatePassed": true, "rateLimitGatePassed": true, "failureBudgetPassed": true,
		"executionLeasesCreated": true, "fluidvirtInvocationsRecorded": true, "mutationsObserved": true,
		"postVerifiesPassed": true, "rollbackWindowsOpen": true,
		"realizedCompressionAggregated": true, "realizedValueAggregated": true,
		"projectedRealizedSeparated": true, "policyGraduationEvidenceProduced": true,
		"productionAutoWithPolicyReadinessCandidate": true, "graduationDecision": "candidate_ready_for_review",
		"canaryCohortCloseoutRecorded": true,
		"candidateCount": float64(3), "selectedCanaryCandidateCount": float64(2),
		"cohortMovementCount": float64(2), "successfulCanaryMovementCount": float64(2),
		"failedCanaryMovementCount": float64(0), "blockedCandidateCount": float64(1),
		"rollbackRequiredCount": float64(0), "rollbackExecutedCount": float64(0),
		"realizedMovementCount": float64(2), "aggregateRealizedMovedIdleValue": float64(450),
		"aggregateRealizedCompressionDelta": 0.02, "aggregateRealizedValue": float64(96),
		"projectedMovedIdleValue": float64(1250), "projectedCompressionDelta": 0.03,
		"projectedValueOpportunity": float64(4800),
		"failureBudgetUsed": 0.0, "failureBudgetRemaining": 1.0,
		"universalGuaranteedSavingsAllowed": false, "universalGuaranteedSavingsClaimed": false,
		"projectedCompressionCountedAsRealized": false, "projectedValueCountedAsRealized": false,
		"estimatedIdleCountedAsMoved": false, "syntheticFleetCountedAsProduction": false,
		"referenceFleetCountedAsProduction": false, "dashboardExecutor": false,
		"fluidvirtPolicyAuthority": false, "fluidvirtControllerAuthority": false,
		"inventoryRuntimeExecutor": false,
		"candidateSelection": map[string]interface{}{
			"candidateSelectionId": "sel-1",
			"sourceObservationWindowRef": "configmap://karl-system/hyperdensity-production-observation-window-v1",
			"candidateCount": float64(3), "selectedCanaryCandidateCount": float64(2), "blockedCandidateCount": float64(1),
			"candidates": candidates, "selectionReason": "stable_window_canary_cohort_top_candidates",
			"selectionPassed": true,
			"evidenceRefs": []interface{}{"artifact://selection"}, "claimBoundary": "candidate selection only",
		},
		"allowlistGate": map[string]interface{}{
			"allowlistGateId": "al-1", "allowlistSource": "configmap://karl-system/canary-allowlist-v1",
			"allowlistedShells": []interface{}{"d3", "d4", "r3", "r4"},
			"allowlistedNamespaces": []interface{}{"prod-canary"},
			"selectedCandidatesAllowlisted": true, "allowlistGatePassed": true,
			"evidenceRefs": []interface{}{"artifact://allowlist"}, "claimBoundary": "allowlist gate only",
		},
		"blastRadiusGate": map[string]interface{}{
			"blastRadiusGateId": "br-1", "maxMovementCount": float64(2), "maxCpuMillicores": float64(500),
			"maxMemoryMiB": float64(512), "maxTenantCount": float64(1),
			"requestedMovementCount": float64(2), "requestedCpuMillicores": float64(250),
			"requestedMemoryMiB": float64(256), "requestedTenantCount": float64(1),
			"blastRadiusExceeded": false, "blastRadiusGatePassed": true,
			"evidenceRefs": []interface{}{"artifact://blast-radius"}, "claimBoundary": "blast radius gate only",
		},
		"sloGate": map[string]interface{}{
			"sloGateId": "slo-1", "sloGuardStatus": "passed", "sloGatePassed": true,
			"evidenceRefs": []interface{}{"artifact://slo"}, "claimBoundary": "slo gate only",
		},
		"rollbackGate": map[string]interface{}{
			"rollbackGateId": "rb-gate-1", "rollbackReady": true, "rollbackGatePassed": true,
			"evidenceRefs": []interface{}{"artifact://rollback-gate"}, "claimBoundary": "rollback gate only",
		},
		"failureBudget": map[string]interface{}{
			"failureBudgetId": "fb-1", "maxFailureCount": float64(1), "maxFailureRate": 0.5,
			"observedFailureCount": float64(0), "observedFailureRate": 0.0,
			"rollbackRequiredCount": float64(0), "rollbackExecutedCount": float64(0),
			"sloFailureCount": float64(0), "mutationFailureCount": float64(0),
			"failureBudgetExceeded": false, "failureBudgetPassed": true,
			"evidenceRefs": []interface{}{"artifact://failure-budget"}, "claimBoundary": "failure budget only",
		},
		"executionLeases": leases,
		"fluidvirtInvocations": invocations,
		"mutationObservations": mutations,
		"postVerifyResults": postVerifies,
		"rollbackWindows": rollbackWindows,
		"realizedCompressionAggregation": map[string]interface{}{
			"aggregationId": "rca-1", "realizedMovementCount": float64(2),
			"aggregateRealizedMovedIdleValue": float64(450), "aggregateRealizedCompressionDelta": 0.02,
			"projectedCompressionExcluded": true, "estimatedValueExcluded": true,
			"movementEvidencePresent": true,
			"evidenceRefs": []interface{}{"artifact://compression-agg"}, "claimBoundary": "realized compression aggregation only",
		},
		"realizedValueAggregation": map[string]interface{}{
			"aggregationId": "rva-1", "aggregateRealizedValue": float64(96),
			"aggregateNetRealizedValue": float64(90), "movementEvidencePresent": true,
			"guaranteedEligible": true, "guaranteeScope": "scoped_eligible_canary_cohort_only",
			"evidenceRefs": []interface{}{"artifact://value-agg"}, "claimBoundary": "realized value aggregation only",
		},
		"projectedRealizedSeparation": map[string]interface{}{
			"separationId": "sep-1", "projectedMovedIdleValue": float64(1250),
			"projectedCompressionDelta": 0.03, "projectedValueOpportunity": float64(4800),
			"aggregateRealizedMovedIdleValue": float64(450), "aggregateRealizedCompressionDelta": 0.02,
			"aggregateRealizedValue": float64(96),
			"projectedCompressionCountedAsRealized": false, "projectedValueCountedAsRealized": false,
			"estimatedIdleCountedAsMoved": false, "syntheticValueExcluded": true, "referenceValueExcluded": true,
			"separationPassed": true,
			"evidenceRefs": []interface{}{"artifact://separation"}, "claimBoundary": "projected/realized separation only",
		},
		"guardedPolicyGraduationEvidence": map[string]interface{}{
			"graduationEvidenceId": "grad-1",
			"sourceCanaryCohortRef": "configmap://karl-system/hyperdensity-production-canary-cohort-expansion-v1",
			"requiredCanaryMovementCount": float64(2), "observedCanaryMovementCount": float64(2),
			"requiredSuccessfulMovementCount": float64(1), "observedSuccessfulMovementCount": float64(2),
			"requiredObservationWindowCount": float64(1), "observedObservationWindowCount": float64(1),
			"failureBudgetWithinLimit": true, "rollbackEvidenceComplete": true,
			"sloEvidenceComplete": true, "accountingEvidenceComplete": true,
			"projectedRealizedSeparationComplete": true, "syntheticReferenceSeparationComplete": true,
			"dashboardExecutorAbsent": true, "fluidvirtAuthorityAbsent": true,
			"graduationEvidenceComplete": true,
			"productionAutoWithPolicyReadinessCandidate": true,
			"productionAutoWithPolicyEnabled": false,
			"graduationDecision": "candidate_ready_for_review",
			"evidenceRefs": []interface{}{"artifact://graduation"}, "claimBoundary": "guarded policy graduation only",
		},
		"canaryCohortCloseout": map[string]interface{}{
			"closeoutId": "close-1", "canaryCohortExpansionId": "cohort-exp-s22-v1", "closeoutStatus": "passed",
			"promotedToGeneralProduction": false, "nextAllowedState": "guarded_policy_review",
			"productionAutoWithPolicyEnabled": false, "auditComplete": true,
			"rollbackWindowsClosedOrOpenWithPolicy": true,
			"evidenceRefs": []interface{}{"artifact://closeout"}, "claimBoundary": "canary cohort closeout only",
		},
		"auditEvents": []interface{}{
			map[string]interface{}{
				"auditEventId": "aud-1", "eventType": "candidate_selected", "occurredAt": "2026-05-14T19:29:00Z",
				"sourceComponent": "Karl-Hyperdensity", "actorType": "controller",
				"summary": "canary cohort candidates selected from stable observation window",
				"evidenceRefs": []interface{}{"artifact://aud-1"}, "claimBoundary": "audit only",
			},
			map[string]interface{}{
				"auditEventId": "aud-2", "eventType": "canary_closed", "occurredAt": "2026-05-14T19:40:00Z",
				"sourceComponent": "Karl-Hyperdensity", "actorType": "controller",
				"summary": "canary cohort completed, graduation evidence produced, production_auto_with_policy remains disabled",
				"evidenceRefs": []interface{}{"artifact://aud-2"}, "claimBoundary": "audit only",
			},
		},
		"sourceOfTruth": map[string]interface{}{
			"runtimeMutation": "FluidVirt", "marketDecision": "Karl-Hyperdensity",
			"identitySignals": "Karl-Inventory", "operatorUI": "Karl-Dashboard (projection only)",
		},
		"safetyInvariants": []interface{}{
			"bounded canary cohort only", "production_auto_with_policy disabled",
			"projected value never counted as realized",
		},
		"claimBoundaries": []interface{}{
			"canary cohort evidence from mutation and post-verify only",
			"graduation evidence is review-only, not activation",
			"no broad production mutation claim",
		},
		"blockers": []interface{}{},
		"warnings": []interface{}{},
		"referenceScenarios": []interface{}{
			map[string]interface{}{"scenarioId": "success", "productionCanaryCohortExecuted": true, "productionAutoWithPolicyEnabled": false},
			map[string]interface{}{"scenarioId": "no_stable_window", "stableObservationWindowObserved": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "no_prior_canary", "priorCanaryMovementEvidenceObserved": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "not_allowlisted", "allowlistGatePassed": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "blast_radius_exceeded", "blastRadiusGatePassed": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "slo_failed", "sloGatePassed": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "rollback_not_ready", "rollbackGatePassed": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "failure_budget_exceeded", "failureBudgetPassed": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "non_canary_movement", "productionCanaryScope": false, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "prod_auto_policy_enabled", "productionAutoWithPolicyEnabled": true, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "projected_realized", "projectedCompressionCountedAsRealized": true, "productionCanaryCohortExecuted": false},
			map[string]interface{}{"scenarioId": "dashboard_executor", "dashboardExecutor": true, "productionCanaryCohortExecuted": false},
		},
	}
}
